### ISSUE TITLE
Lora/SX126x is missing BUSY pin connection to RP2040

### ISSUE THREAD

**Issue by cHemingway** [01Space/RP2040-1.14LCD#2]
The SX126x signals needs the BUSY pin to signal to the microcontroller it is ready to accept a command.

This is used in many libraries, for instance RadioLib uses it for every [SPI Transaction](https://github.com/jgromes/RadioLib/blob/ae7065da7bae367ef0e0b12c758deb5c691ddfc7/src/modules/SX126x/SX126x.cpp#L1644), and so the [examples](https://github.com/jgromes/RadioLib/blob/ae7065da7bae367ef0e0b12c758deb5c691ddfc7/examples/SX126x/SX126x_Receive/SX126x_Receive.ino#L30) ask for it.

The official LoRaWAN stack uses it also, in the function [`SX126xWaitOnBusy()`](https://github.com/Lora-net/LoRaMac-node/blob/f0c08bb0fd71c78f24dcfaed7d1c9d083f373446/src/radio/sx126x/sx126x.c#L142)

For now, I can solder the pin on the [module](https://docs.ai-thinker.com/_media/lora/docs/ra-01sh_specification.pdf) to pin 23 (which is next to it on the board), but it would be useful if it was connected by default.

**Comment by 01Space** [comment]
Rp2040 pin15 has been connected to sx126x busy
// SX1262 has the following connections:
// NSS pin:   14
// DIO1 pin:  13
// NRST pin:  7
// BUSY pin:  15
SX1262 radio = new Module(14, 13, 7, 15);

I'm sorry! I forgot to update the pin assignment picture
https://github.com/01Space/RP2040-1.14LCD/tree/main/Arduino/RP2040-SX126X

**Comment by cHemingway** [comment]
No worries, Can you update the image so I can close the issue?

**Comment by 01Space** [comment]
I have updated it

**Comment by cHemingway** [comment]
Thanks!
